---
title: "RWorkSheet#5b_group(Celestra,Caneso,Arenal)"
author: "Rovel Jan Caneso"
date: "2024-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Libraries**
```{r}
library(rvest)
library(httr)
library(polite)
library(dplyr)
library(stringr)
library(knitr) 
```

```{r}
# Define URLs
url <- "https://www.amazon.com/"
session <- bow(url, 
               user_agent = "Educational")
session

urls <- c('https://www.amazon.com/s?k=graphics+card&crid=6809YKENO5VZ&sprefix=graphics+%2Caps%2C516&ref=nb_sb_ss_ts-doa-p_1_9', 
          'https://www.amazon.com/s?k=laptop&crid=15FICF43OPKJ2&sprefix=laptop%2Caps%2C1359&ref=nb_sb_ss_ts-doa-p_1_6',
          'https://www.amazon.com/s?k=pc+cases&crid=3232B9XX8J30L&sprefix=pccase%2Caps%2C674&ref=nb_sb_ss_ts-doa-p_3_6',
          'https://www.amazon.com/s?k=monitors&crid=UGL8HSJMO1RM&qid=1732067471&refresh=1&sprefix=monitors%2Caps%2C588&ref=sr_pg_1',
          'https://www.amazon.com/s?k=cpu&crid=3DBICI2YNNKHJ&sprefix=cpu%2Caps%2C768&ref=nb_sb_noss_1')
```
```{r}
#code to extract urls of the 10 products per category
graphic_links <- read_html(urls[1]) %>%
    html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
    html_attr("href") %>%
    unique() %>%
    paste0("https://www.amazon.com", .)

laptop_links <- read_html(urls[2]) %>%
    html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
    html_attr("href") %>%
    unique() %>%
    paste0("https://www.amazon.com", .)

case_links <- read_html(urls[3]) %>%
    html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
    html_attr("href") %>%
    unique() %>%
    paste0("https://www.amazon.com", .)

monitor_links <- read_html(urls[4]) %>%
    html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
    html_attr("href") %>%
    unique() %>%
    paste0("https://www.amazon.com", .)

cpu_links <- read_html(urls[5]) %>%
    html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
    html_attr("href") %>%
    unique() %>%
    paste0("https://www.amazon.com", .)

#df containing the url of 10 products per category
product_category_links <- data.frame(
  GraphicsCard = graphic_links[1:10],
  Laptops = laptop_links[1:10],
  PCcase = case_links[1:10],
  Monitor = monitor_links[1:10],
  CPU = cpu_links[1:10]
)
```
```{r}
#url of 10 products split into each of their category
graphics_products_link <- product_category_links$GraphicsCard
laptop_products_link <- product_category_links$Laptops
PCcase_products_link <- product_category_links$PCcase
monitor_products_link <- product_category_links$Monitor
CPU_products_link <- product_category_links$CPU
```
```{r}
scrape_reviews <- function(url) {
  page <- read_html(url)
          
  #scraping the name of each product          
  product_name <- page %>%
    html_nodes(".a-size-large.product-title-word-break") %>%
    html_text(trim = T) %>%
    strsplit(" ") %>%                
    .[[1]] %>%                       
    .[1:4] %>%
    gsub("\\,", "", .) %>%
    paste(collapse = " ")  
  
  #scraping username of each reviewers
  user_name_reviews <- page %>%
    html_nodes(".a-profile-name") %>%
    html_text() %>%
    unique()
  
  #scraping review dates of users
  review_dates <- page %>%
    html_nodes(".a-size-base.a-color-secondary.review-date") %>%
    html_text() %>%
    gsub(".*on ", "", .)
  
  #scraping reviewer individual rating
  reviewer_rating <- page %>%
    html_nodes(".a-icon-alt") %>%
    html_text() %>%
    gsub(" out.*", "", .) %>%
    .[grepl("^[0-9.]+$", .)] %>% 
    as.numeric()
  
  #scraping review title
  review_title <- page %>%
    html_nodes(".a-size-base.a-link-normal.review-title.a-color-base.review-title-content.a-text-bold span:nth-of-type(2)") %>%
    html_text()
  
  #scraping text reviews of each user
  text_reviews <- page %>%
    html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>%
    html_text(trim = TRUE)
    
  data.frame(
    Product_Name = rep(product_name, 20),
    Reviewer_Names = user_name_reviews[2:21],
    Review_Date = review_dates[1:20],
    Individual_Ratings = reviewer_rating[1:20],
    Review_Title = review_title[1:20],
    Text_Reviews = text_reviews[1:20]
    )
}

#applying scrape reviews to each of the product category's links
graphic_reviews <- lapply(graphics_products_link, scrape_reviews)
laptop_reviews <- lapply(laptop_products_link, scrape_reviews)
case_reviews <- lapply(PCcase_products_link, scrape_reviews)
monitor_reviews <- lapply(monitor_products_link, scrape_reviews)
CPU_reviews <- lapply(CPU_products_link, scrape_reviews)

```

```{r}
#combining the data frames of the product reviews per category
graphics_reviews_df <- do.call(rbind, graphic_reviews)
laptop_reviews_df <- do.call(rbind, laptop_reviews)
case_reviews_df <- do.call(rbind, case_reviews)
monitor_reviews_df <- do.call(rbind, monitor_reviews)
CPU_reviews_df <- do.call(rbind, CPU_reviews)
```
```{r}
#code to view the contents of the product's data frame
print(graphics_reviews_df)
print(laptop_reviews_df)
print(case_reviews_df)
print(monitor_reviews_df)
print(CPU_reviews_df)
```
```{r}
#write.csv(graphics_reviews_df, "GraphicsCard_Reviews.csv")
#write.csv(laptop_reviews_df, "Laptops_Reviews.csv")
#write.csv(case_reviews_df, "PCcase_Reviews.csv")
#write.csv(monitor_reviews_df, "Monitor_Reviews.csv")
#write.csv(CPU_reviews_df, "CPU_Reviews.csv")
```






